CPP := g++.exe
CC := gcc.exe
CFLAGS := -I../src -O3 -march=i686 -ffast-math -fomit-frame-pointer -falign-loops -falign-jumps -falign-functions

SRC := $(wildcard *.c)

OBJ := $(patsubst %c,%o,$(SRC))

LIBS :=

.PHONY: all
all: ElkulatorTest.exe

.PHONY: clean
clean:
	rm -f *.o
	rm -f *.exe

ElkulatorTest.exe: $(OBJ) path.o
	$(CC) $^ -o $@ $(LIBS)

path.o: ../src/path.c
	$(CC) $(CFLAGS) -c $<

%.o: %.c
	$(CC) $(CFLAGS) -c $<

%.o: %.cc
	$(CPP) $(CFLAGS) -c $<

