#!/bin/bash
if [[ "$OSTYPE" == "darwin"* ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
SCRIPTPATH=$($READLINK -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
REPODIR=$(dirname $SCRIPTDIR)

LOGPATH=$REPODIR/allegro.log
if [ -f $LOGPATH ]; then
  rm $LOGPATH
fi

pushd $REPODIR
touch $LOGPATH
./elkulator $* &
tail -f $LOGPATH
popd

